#!/bin/bash

echo ""
echo "This script will install Unicorn Hat libraries"
echo "and dependencies for both Python 2 and 3."
echo ""
echo "This process may take several minutes."
echo ""
echo "--- Warning ---"
echo ""
echo "Always be careful when running scripts and commands"
echo "copied from the internet. Ensure they are from a"
echo "trusted source."
echo ""
echo "If you want to see what this script does before"
echo "running it, you should run:"
echo "    \curl -sS get.pimoroni.com/unicornhat"
echo ""
echo ""


read -r -p "Do you wish to continue? [y/N] " response < /dev/tty
response=${response,,}

if [[ $response =~ ^(yes|y)$ ]]
then
	echo ""
	echo "Updating package indexes..."
	sudo apt-get update
	
	echo ""
	echo "Installing UnicornHat requirements..."
	sudo apt-get --yes --force-yes install python-pip python3-pip python-dev python3-dev
	
	echo ""
	echo "Installing UnicornHat for Python 2..."
	sudo pip install unicornhat

	echo ""
	echo "Installing UnicornHat for Python 3..."
	sudo pip-3.2 install unicornhat

	echo ""
	echo "All done!"
	echo "For examples"
	echo "see https://github.com/pimoroni/UnicornHat/tree/master/python/examples"
	echo "And visit forums.pimoroni.com for support"	
	echo "Have fun!"
	echo ""

else
	echo ""
	echo "Aborting..."
	echo ""
fi
