#!/bin/sh

### BEGIN INIT INFO
# Provides:        unicorn
# Required-Start:  $network $syslog
# Required-Stop:   $network $syslog
# Default-Start:   2 3 4 5
# Default-Stop: 
# Short-Description: Start Unicorn hat daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

DAEMON=/usr/sbin/unicornd
PIDFILE=/var/run/unicornd.pid

test -x $DAEMON || exit 5

case $1 in
	start)
		log_daemon_msg "Starting Unicorn Hat server" "unicornd"
  		start-stop-daemon --start -b --quiet --oknodo --pidfile $PIDFILE -m --startas $DAEMON -- $UNICORND_OPTS
		status=$?
		log_end_msg $status
  		;;
	stop)
		log_daemon_msg "Stopping Unicorn Hat server" "unicornd"
  		start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
		log_end_msg $?
		rm -f $PIDFILE
  		;;
	restart|force-reload)
		$0 stop && sleep 2 && $0 start
  		;;
	try-restart)
		if $0 status >/dev/null; then
			$0 restart
		else
			exit 0
		fi
		;;
	reload)
		exit 3
		;;
	status)
		status_of_proc $DAEMON "Unicorn Hat server"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
		exit 2
		;;
esac
